stages:
  data_ingestion:
    cmd: python src/Kidney_Disease_Classification/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/Kidney_Disease_Classification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs: 
      - artifacts/data_ingestion/kidney-ct-scan-image


  prepare_base_model:
    cmd: python src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py
    deps: 
      - src/Kidney_Disease_Classification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params: 
      - IMAGE_SIZE
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
      - INCLUDE_TOP
    outs: 
      - artifacts/prepare_base_model

  training:
    cmd: python src/Kidney_Disease_Classification/pipeline/stage_03_model_trainer.py
    deps:
      - src/Kidney_Disease_Classification/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    params: 
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training


  evaluation:
    cmd: python src/Kidney_Disease_Classification/pipeline/stage_04_model_evaluation.py
    deps:
      - src/Kidney_Disease_Classification/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false

